{
    "Id": "ReminderErrorContent",
    "Type": 240,
    "Languages": [
        {
            "Body": "The following reminder caused an error and was removed from the schedule.\nTarget Site: {0}(id: {1})\nTarget Reminder: {2}(id: {3})\nError Message: {4}\nError StackTrace: {5}"
        },
        {
            "Language": "zh",
            "Body": "以下提醒引起了错误，并已从计划中删除。\n目标站点: {0}(id: {1})\n目标提醒: {2}(id: {3})\n错误消息: {4}\n错误堆栈跟踪: {5}"
        },
        {
            "Language": "ja",
            "Body": "以下のリマインダーでエラーが発生したため、スケジュールから削除しました。\n対象サイト: {0}(id: {1})\n対象リマインダー: {2}(id: {3})\nエラーメッセージ: {4}\nエラースタックトレース: {5}"
        },
        {
            "Language": "de",
            "Body": "Die folgende Erinnerung verursachte einen Fehler und wurde aus dem Zeitplan entfernt.\nZielwebsite: {0}(id: {1})\nZielerinnerung: {2}(id: {3})\nFehlermeldung: {4}\nFehler StackTrace: {5}"
        },
        {
            "Language": "ko",
            "Body": "다음 알림에서 오류가 발생했기 때문에 일정에서 삭제했습니다.\n대상 사이트: {0}(id: {1})\n대상 알림: {2}(id: {3})\n오류 메시지: {4}\n오류 스택 추적: {5}"
        },
        {
            "Language": "es",
            "Body": "El siguiente recordatorio provocó un error y se eliminó de la programación.\nSitio de destino: {0}(id: {1})\nRecordatorio de destino: {2}(id: {3})\nMensaje de error: {4}\nSeguimiento de pila de errores: {5}"
        },
        {
            "Language": "vn",
            "Body": "Lời nhắc sau đây đã gây ra lỗi và bị xóa khỏi lịch biểu.\nTrang web mục tiêu: {0}(id: {1})\nLời nhắc mục tiêu: {2}(id: {3})\nThông báo lỗi: {4}\nTheo dõi ngăn xếp lỗi: {5}"
        }
    ]
}